export const LocationName = [
    { value: 'Bhaktapur Durbar Square', label: 'Bhaktapur Durbar Square' },
    { value: 'Taumadhi Square', label: 'Taumadhi Square' },
    { value: 'Pottery Square', label: 'Pottery Square' },
    { value: 'Dattatreya Square', label: 'Dattatreya Square' },
    { value: 'Nagarkot', label: 'Nagarkot' },
    { value: 'Changu Narayan', label: 'Changu Narayan' },
    { value: 'Siddha Pokhari', label: 'Siddha Pokhari' },
    { value: 'Bhairavnath Temple', label: 'Bhairavnath Temple' },
    { value: 'Nyatapola Temple', label: 'Nyatapola Temple' },
    { value: '55 Windows Palace', label: '55 Windows Palace' },

    // Kathmandu
    { value: 'Thamel', label: 'Thamel' },
    { value: 'Durbar Square', label: 'Durbar Square' },
    { value: 'Boudhanath', label: 'Boudhanath' },
    { value: 'Pashupatinath', label: 'Pashupatinath' },
    { value: 'Swayambhunath', label: 'Swayambhunath' },
    { value: 'Kirtipur', label: 'Kirtipur' },
    { value: 'Budhanilkantha', label: 'Budhanilkantha' },
    { value: 'Kalimati', label: 'Kalimati' },
    { value: 'Maitidevi', label: 'Maitidevi' },
    { value: 'Gaushala', label: 'Gaushala' },
    { value: 'Chabahil', label: 'Chabahil' },
    { value: 'Maitighar', label: 'Maitighar' },
    { value: 'New Baneswor', label: 'New Baneswor' },
    { value: 'Old Baneswor', label: 'Old Baneswor' },
    { value: 'Sinamangal', label: 'Sinamangal' },
    { value: 'Kalopul', label: 'Kalopul' },
    { value: 'Dhobighat', label: 'Dhobighat' },
    { value: 'Bagbazar', label: 'Bagbazar' },
    { value: 'Putalisadak', label: 'Putalisadak' },
    { value: 'Kamalpokhari', label: 'Kamalpokhari' },
    { value: 'Naxal', label: 'Naxal' },
    { value: 'Baluwatar', label: 'Baluwatar' },
    { value: 'Maharajgunj', label: 'Maharajgunj' },
    { value: 'Basundhara', label: 'Basundhara' },
    { value: 'Dhapasi', label: 'Dhapasi' },
    { value: 'Buddha Nagar', label: 'Buddha Nagar' },
    { value: 'Kalanki', label: 'Kalanki' },
    { value: 'Teku', label: 'Teku' },
    { value: 'Tripureshwor', label: 'Tripureshwor' },
    { value: 'Sitapaila', label: 'Sitapaila' },
    { value: 'Swoyambhu', label: 'Swoyambhu' },
    { value: 'Balkhu', label: 'Balkhu' },
    { value: 'Kuleshwor', label: 'Kuleshwor' },
    { value: 'Chakupat', label: 'Chakupat' },
    { value: 'Jadibuti', label: 'Jadibuti' },

    // Lalitpur
    { value: 'Patan Durbar Square', label: 'Patan Durbar Square' },
    { value: 'Ashokan Stupas', label: 'Ashokan Stupas' },
    { value: 'Mahaboudha Temple', label: 'Mahaboudha Temple' },
    { value: 'Taleju Temple', label: 'Taleju Temple' },
    { value: 'Bhimsen Tower', label: 'Bhimsen Tower' },
    { value: 'Hiranya Varna Mahavihar', label: 'Hiranya Varna Mahavihar' },
    { value: 'Jagat Narayan Temple', label: 'Jagat Narayan Temple' },
    { value: 'Tusha Hiti', label: 'Tusha Hiti' },
    { value: 'Pulchowk', label: 'Pulchowk' },
    { value: 'Balkumari', label: 'Balkumari' },
    { value: 'Bhanimandal', label: 'Bhanimandal' },
    { value: 'Ekantakuna', label: 'Ekantakuna' },
    { value: 'Satdobato', label: 'Satdobato' },
    { value: 'Imadol', label: 'Imadol' },
    { value: 'Bhaisepati', label: 'Bhaisepati' },
];
